name: CI/CD Pipeline for Docker Compose

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-docker@v2
              with:
                  docker-version: '20.10'
                  buildx-version: latest
                  qemu-version: latest

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image using Docker Compose
              run: |
                  docker-compose -f docker-compose.yml build
                  docker-compose -f docker-compose.yml push
